# https://docs.spring.io/spring-boot/docs/2.0.0.RELEASE/reference/htmlsingle/#common-application-properties

# SPRING
spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  mvc:
    static-path-pattern: '/assets/**'
  resources:
    static-locations: 'classpath:/assets/'

  #json
  jackson:
    locale: zh_CN
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# LOGGING
logging:
  config: 'classpath:logback.xml'